Removed NameError
Typo - alcehmy instead of 'alchemy'

---> 17 engine = sqlalcehmy.create_engine(SQL_DB_URI)
NameError: name 'sqlalcehmy' is not defined